name: 'deploy'
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Repo Name
        id: repo_name
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY##*/})"

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: 'ssh://dokku@staging.discours.io:22/${{ steps.repo_name.outputs.repo }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}