name: 'deploy'
on:
  push:
    branches:
      - main
      - feature/sse-connect

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run check

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure 'test' job is completed before deploying
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Vercel CLI
      run: |
        npm install -g vercel
        vercel --version

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
